### ISSUE TITLE
should be cleaned up

### ISSUE THREAD

**Issue by langdon** [BU-Spark/se-team-mejia#3]
While these "helpful hints" on problems for people working on this app are great, the screenshots are a bit "leaky". As in, they reveal too much about your personal computer and its setup. You should crop these images down or fuzz out the parts about "your computer".

https://github.com/BU-Spark/se-team-mejia/blob/92f992fb49453c65ae3157c28aa7cdf575db66b0/README.md?plain=1#L186
https://github.com/BU-Spark/se-team-mejia/blob/92f992fb49453c65ae3157c28aa7cdf575db66b0/README.md?plain=1#L194
https://github.com/BU-Spark/se-team-mejia/blob/92f992fb49453c65ae3157c28aa7cdf575db66b0/README.md?plain=1#L216

**Comment by drago1234** [comment]
Problem Fixed
