### ISSUE TITLE
aid org sites not opening correctly

### ISSUE THREAD

**Issue by langdon** [BU-Spark/se-team-mejia#5]
when you add a aid org, there is an issue where the urls are not being opened properly. For example, entered "www.example.com" and when you click you go to https://bu-spark.github.io/se-team-mejia/www.example.com

**Comment by mikethegoblin** [comment]
This issue is caused by href treating "www.example.com" as a relative url path. We fixed it by converting url paths like "www.example.com" to absolute url path "https://www.example.com". Now, when you click on website, it will redirect you to the absolute url.
